apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ibf2e7g0s-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:6e26359f33fc4ff87399bab83ff00f74a98e7f5f@sha256:9f51dbdaa65005b874836187ddcbd5689cd82c18178f309cf47221dfb79b0549
          name: container-image
